#!/usr/bin/env ruby
# frozen_string_literal: true

# Fetches Indonesian national holidays + cuti bersama from api-hari-libur and
# writes them to data/holidays.json. Run by .github/workflows/update-holidays.yml
# on a schedule so the committed data stays accurate without manual edits.
#
# Design notes:
# - The app reads only the committed JSON, never the network at runtime.
# - A year is only overwritten when the fetch succeeds and looks sane, so a bad
#   or empty API response can never wipe good committed data.
# - Years already in the file are preserved even if the API stops serving them.

require 'net/http'
require 'json'
require 'uri'
require 'date'

API_BASE = 'https://api-hari-libur.vercel.app/api'
DATA_FILE = File.expand_path('../data/holidays.json', __dir__)

# Minimum entries for a fetched year to be trusted (a real year has ~15-28).
MIN_SANE_ENTRIES = 5

# Keyword -> type. Checked against a downcased description; first match wins,
# default :national. Mirrors the original app's National/Religious/Cultural split.
RELIGIOUS_KEYWORDS = [
  'isra', 'idul fitri', 'idul adha', 'tahun baru islam', 'maulid', 'asyura',
  'nyepi', 'waisak', 'jumat agung', 'wafat yesus', 'paskah', 'kebangkitan',
  'kenaikan yesus', 'natal', 'ramadhan'
].freeze
CULTURAL_KEYWORDS = ['imlek', 'cap go meh'].freeze

def classify(description)
  d = description.downcase
  return 'religious' if RELIGIOUS_KEYWORDS.any? { |k| d.include?(k) }
  return 'cultural' if CULTURAL_KEYWORDS.any? { |k| d.include?(k) }

  'national'
end

def fetch_year(year)
  uri = URI("#{API_BASE}?year=#{year}")
  3.times do |attempt|
    begin
      res = Net::HTTP.start(uri.host, uri.port, use_ssl: true, open_timeout: 10, read_timeout: 15) do |http|
        http.get(uri.request_uri)
      end
      return nil if res.code == '404' # year not published yet

      raise "HTTP #{res.code}" unless res.code == '200'

      body = JSON.parse(res.body)
      list = body.is_a?(Hash) ? (body['data'] || []) : body
      return list if list.is_a?(Array)
    rescue StandardError => e
      warn "  attempt #{attempt + 1} for #{year} failed: #{e.message}"
      sleep(2)
    end
  end
  raise "could not fetch #{year} after retries"
end

def normalize(list)
  seen = {}
  list.each do |h|
    date = h['date']
    name = h['description']
    next unless date && name
    next if seen.key?(date) # keep first entry for a date

    seen[date] = { 'date' => date, 'name' => name, 'type' => classify(name) }
  end
  seen.values.sort_by { |e| e['date'] }
end

existing =
  if File.exist?(DATA_FILE)
    (JSON.parse(File.read(DATA_FILE))['years'] || {})
  else
    {}
  end

years = existing.dup
current = Time.now.year

(current - 1..current + 2).each do |year|
  key = year.to_s
  begin
    list = fetch_year(year)
    if list.nil?
      puts "#{year}: not published yet (404), keeping #{existing.key?(key) ? 'existing data' : 'nothing'}"
      next
    end

    if list.size < MIN_SANE_ENTRIES
      puts "#{year}: only #{list.size} entries (< #{MIN_SANE_ENTRIES}), suspicious — keeping existing"
      next
    end

    # Fixed-date anchors that must appear every year. Missing any of them means
    # the scrape is misaligned/wrong, not just sparse — reject rather than commit.
    dates = list.map { |h| h['date'] }
    anchors = ["#{year}-01-01", "#{year}-08-17", "#{year}-12-25"]
    missing = anchors.reject { |a| dates.include?(a) }
    unless missing.empty?
      puts "#{year}: missing fixed anchors #{missing.join(', ')} — looks wrong, keeping existing"
      next
    end

    years[key] = normalize(list)
    puts "#{year}: #{years[key].size} holidays"
  rescue StandardError => e
    puts "#{year}: ERROR (#{e.message}) — keeping existing data"
  end
end

sorted = years.keys.sort.to_h { |k| [k, years[k]] }
output = {
  '_comment' => 'Auto-generated by scripts/fetch_holidays.rb. Do not edit by hand.',
  'source' => API_BASE,
  'years' => sorted
}

File.write(DATA_FILE, "#{JSON.pretty_generate(output)}\n")
puts "Wrote #{DATA_FILE} (#{sorted.size} years: #{sorted.keys.join(', ')})"
